{"name": "test_fee_error[test_fee1]", "status": "passed", "description": "验证各种场景下fees 传入错误、异常参数的情况", "attachments": [{"name": "log", "source": "2e488de2-64ec-4b4f-ae47-5f4e73d0a3c2-attachment.txt", "type": "text/plain"}], "parameters": [{"name": "test_fee", "value": "{'error_data': 0.0, 'error_return': 13}"}], "start": 1692797196165, "stop": 1692797197481, "uuid": "9347cad2-3d6f-43f3-b498-7a91fc4751c9", "historyId": "a2ded051846d3ab9b9fedd7b10624d3c", "testCaseId": "16249f0aa1339e81c78d877757b8f94a", "fullName": "cases.stake.test_fee.TestFee#test_fee_error", "labels": [{"name": "parentSuite", "value": "cases.stake"}, {"name": "suite", "value": "test_fee"}, {"name": "subSuite", "value": "TestFee"}, {"name": "host", "value": "wang"}, {"name": "thread", "value": "60782-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "cases.stake.test_fee"}]}