{"name": "test_fee_error[test_fee0]", "status": "passed", "description": "验证各种场景下fees 传入错误、异常参数的情况", "attachments": [{"name": "log", "source": "b790a9e4-7090-4c12-8414-77889078d41d-attachment.txt", "type": "text/plain"}], "parameters": [{"name": "test_fee", "value": "{'error_data': 0, 'error_return': 13}"}], "start": 1692797194886, "stop": 1692797196159, "uuid": "4708a5b0-9fe3-4cab-b0c8-8d9ee8693172", "historyId": "46ccd50e82c5801e435c2197ec2ae80f", "testCaseId": "16249f0aa1339e81c78d877757b8f94a", "fullName": "cases.stake.test_fee.TestFee#test_fee_error", "labels": [{"name": "parentSuite", "value": "cases.stake"}, {"name": "suite", "value": "test_fee"}, {"name": "subSuite", "value": "TestFee"}, {"name": "host", "value": "wang"}, {"name": "thread", "value": "60782-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "cases.stake.test_fee"}]}